sudo: false
language: objective-c
osx_image: xcode8
script: "make check"
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Skull'
branches:
  only:
    - master
  except:
    - /^v[0-9]/
